import { useCallback, useState } from 'react'
import { Dna, Download, Eye, FileJson } from 'lucide-react'
import { useI18n } from '../i18n'
import { fetchGenBankRecord, fetchGeneticRecords } from '../services/ncbi'
import { useResource } from '../hooks/useResource'
import { StatusMessage } from '../components/StatusMessage'
import { downloadText, toCsv, toFasta } from '../utils/exports'
import type { GeneticRecord } from '../types'

export function GeneticsPage({ compact = false }: { compact?: boolean }) {
  const { t } = useI18n(); const [name, setName] = useState('Catopuma badia'); const [page, setPage] = useState(0); const [selected, setSelected] = useState<GeneticRecord | null>(null); const [sequence, setSequence] = useState<string | null>(null); const [genes, setGenes] = useState<string[]>([])
  const loader = useCallback(() => fetchGeneticRecords(page, 25, name), [name, page]); const resource = useResource(loader); const result = resource.data
  const loadSequence = async (record: GeneticRecord) => { setSelected(record); try { const value = await fetchGenBankRecord(record.accession); setSequence(value.sequence); setGenes([...new Set(value.genes.map((gene) => gene.geneName))]); } catch { setSequence(null) } }
  const downloadable = selected && sequence ? [{ ...selected, sequence }] : []
  const mitochondrial = result?.records.filter((record) => record.molecule?.toLowerCase().includes('mitochond')).length || 0
  const projects = new Set(result?.records.map((record) => record.bioProject).filter(Boolean)).size
  return <div className={compact ? 'explorer-panel' : 'page'}>{!compact && <PageHeader />}
    <div className="toolbar data-toolbar"><label className="filter species-filter"><span>{t('common.scientificName')}</span><select value={name} onChange={(event) => { setName(event.target.value); setPage(0) }}><option>Catopuma badia</option><option>Pardofelis badia</option></select></label><button className="button primary" onClick={resource.load} disabled={resource.loading}><Dna size={17} />{t('common.search')}</button>{result && <><button className="button quiet" onClick={() => downloadText('genetic-records.csv', toCsv(result.records as unknown as Array<Record<string, unknown>>), 'text/csv')}>{t('genetics.exportCsv')}</button><button className="button quiet" onClick={() => downloadText('genetic-records.json', JSON.stringify(result.records, null, 2), 'application/json')}>{t('genetics.exportJson')}</button></>}<span className="data-badge">NCBI / GenBank · E-utilities</span></div>
    {result && <div className="metric-grid genetics-metrics"><Metric label={t('genetics.totalRecords')} value={result.count} /><Metric label={t('genetics.uniqueAccessions')} value={new Set(result.records.map((record) => record.accession)).size} /><Metric label={t('genetics.totalGenes')} value={genes.length || t('common.pending')} /><Metric label={t('genetics.mitochondrial')} value={mitochondrial} /><Metric label={t('genetics.bioProjects')} value={projects} /></div>}
    {resource.loading && <StatusMessage loading />}{resource.error && <StatusMessage error onRetry={resource.load} />}{result && <><div className="result-count"><strong>{result.count}</strong> {t('genetics.totalFound')}</div><div className="panel table-wrap"><table><thead><tr><th>{t('genetics.accession')}</th><th>{t('genetics.organism')}</th><th>{t('genetics.molecule')}</th><th>{t('genetics.length')}</th><th>{t('genetics.database')}</th><th>{t('common.actions')}</th></tr></thead><tbody>{result.records.map((record) => <tr key={record.sourceId}><td><a href={record.originalUrl} target="_blank" rel="noreferrer">{record.accession}</a></td><td><em>{record.organism || record.scientificName}</em></td><td>{record.molecule || t('common.noData')}</td><td>{record.sequenceLength || t('common.noData')}</td><td>{record.database || t('common.noData')}</td><td><button className="icon-button" title={t('genetics.viewSequence')} aria-label={t('genetics.viewSequence')} onClick={() => loadSequence(record)}><Eye size={15} /></button></td></tr>)}</tbody></table></div><div className="pagination"><button className="text-button" disabled={page === 0} onClick={() => setPage(page - 1)}>{t('common.previous')}</button><span>{page + 1} / {Math.max(1, Math.ceil(result.count / result.limit))}</span><button className="text-button" disabled={result.offset + result.limit >= result.count} onClick={() => setPage(page + 1)}>{t('common.next')}</button></div></>}{selected && <section className="panel sequence-panel"><div className="panel-title"><div><p className="eyebrow">{t('genetics.sequenceViewer')}</p><h2>{selected.accession}</h2></div><a href={selected.originalUrl} target="_blank" rel="noreferrer">{t('common.original')}</a></div><p className="muted">{selected.organism || selected.scientificName} · {sequence?.length || selected.sequenceLength || t('common.noData')} bp</p>{genes.length > 0 && <p className="muted">{t('genetics.genesFound')}: {genes.join(', ')}</p>}{sequence ? <><pre className="sequence-text">{sequence.slice(0, 20000)}{sequence.length > 20000 ? '…' : ''}</pre><div className="actions"><button className="button quiet" onClick={() => navigator.clipboard?.writeText(sequence)}>{t('genetics.copyFasta')}</button><button className="button primary" onClick={() => downloadText(`${selected.accession}.fasta`, toFasta(downloadable), 'text/plain')}><Download size={15} />FASTA</button></div></> : <StatusMessage error />}</section>}{!result && !resource.loading && !resource.error && <StatusMessage empty />}</div>
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div> }
function PageHeader() { const { t } = useI18n(); return <section className="page-header"><p className="eyebrow">{t('pages.genetics.kicker')}</p><h1>{t('pages.genetics.title')}</h1><p>{t('pages.genetics.description')}</p><div className="notice"><Dna size={18} /><span>{t('genetics.warning')}</span><FileJson size={18} /></div></section> }
