import { useCallback } from 'react'
import { useResource } from '../hooks/useResource'
import { fetchLiterature } from '../services/literature'
import { fetchCrossrefLiterature } from '../services/crossref'
import { fetchDryadDatasets } from '../services/dryad'
import { useI18n } from '../i18n'
import { StatusMessage } from '../components/StatusMessage'
import { BookOpen } from 'lucide-react'

export function ResearchPage({ compact = false }: { compact?: boolean }) {
  const { t } = useI18n(); const loader = useCallback(async () => { const results = await Promise.allSettled([fetchLiterature(25), fetchCrossrefLiterature(10), fetchDryadDatasets(10)]); const records = results.flatMap((result) => result.status === 'fulfilled' ? result.value : []); return [...new Map(records.map((record) => [`${record.source}:${record.sourceId}`, record])).values()] }, []); const resource = useResource(loader)
  return <div className={compact ? 'explorer-panel' : 'page'}>{!compact && <section className="page-header"><p className="eyebrow">{t('pages.research.kicker')}</p><h1>{t('pages.research.title')}</h1><p>{t('pages.research.description')}</p></section>}{!compact && <section className="research-themes"><p className="eyebrow">{t('research.themesTitle')}</p>{['distribution', 'genetics', 'taxonomy', 'conservation', 'habitat'].map((theme) => <div key={theme}><BookOpen size={16} /><span>{t(`research.theme.${theme}`)}</span></div>)}</section>}<div className="toolbar"><button className="button primary" onClick={resource.load} disabled={resource.loading}>{t('common.search')}</button><span className="data-badge">PubMed · Crossref · Dryad · public metadata</span></div><StatusMessage loading={resource.loading} error={resource.error} onRetry={resource.load} empty={!!resource.data && resource.data.length === 0} />{resource.data && <div className="literature-list">{resource.data.map((record) => <article className="panel literature-card" key={`${record.source}-${record.sourceId}`}><p className="eyebrow">{record.source} · {record.year || t('common.noData')}</p><h2>{record.title || t('common.noData')}</h2><p className="muted">{record.authors || t('common.noData')}<br />{record.journal || t('common.noData')}</p><p className="provenance">{record.source} · {record.sourceId} · {t('common.retrieved')}: {record.retrievedAt.slice(0, 10)}</p><div><a href={record.originalUrl} target="_blank" rel="noreferrer">{t('common.openSource')}</a>{record.doi && <a className="doi-link" href={`https://doi.org/${record.doi}`} target="_blank" rel="noreferrer">DOI: {record.doi}</a>}</div><p className="metadata-note">{t('research.metadataNote')}</p></article>)}</div>}</div>
}
