import { useEffect, useState } from 'react'
import { HashRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowUpRight, BarChart3, Database, Dna, Globe2, Leaf, Menu, Search, ShieldCheck, X } from 'lucide-react'
import { useI18n } from './i18n'
import { fetchGeneticRecords } from './services/ncbi'
import { fetchOccurrences } from './services/gbif'
import { useResource } from './hooks/useResource'
import { MapView } from './components/MapView'
import { StatusMessage } from './components/StatusMessage'
import type { OccurrenceRecord } from './types'
import { DistributionPage, GeneticsPage, DataExplorerPage, TaxonomyPage, ResearchPage, DataAvailabilityPage, SpeciesProfilePage } from './pages'
import './styles.css'

const routes = [
  ['genetics', 'nav.genetics', Dna], ['distribution', 'nav.distribution', Globe2], ['taxonomy', 'nav.taxonomy', Database], ['profile', 'nav.profile', Leaf], ['availability', 'nav.availability', BarChart3], ['research', 'nav.research', Search],
  ['conservation', 'nav.conservation', ShieldCheck], ['explorer', 'nav.explorer', Database], ['sources', 'nav.sources', Leaf], ['methodology', 'nav.methodology', Database]
] as const

function Header() {
  const { locale, setLocale, t } = useI18n(); const [open, setOpen] = useState(false)
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false) }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close) }, [])
  return <header className="site-header"><Link className="brand" to="/"><img className="project-logo" src="./project-logo.jpeg" alt={t('common.projectLogoAlt')} /><span><strong>{t('brand')}</strong><small>{t('brandSub')}</small></span></Link>
    <button className="menu-button" aria-label={t('common.menu')} aria-expanded={open} aria-controls="site-navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
    <nav id="site-navigation" aria-label={t('common.navigation')} className={open ? 'nav open' : 'nav'}>{routes.map(([path, label, Icon]) => <NavLink onClick={() => setOpen(false)} key={path} to={`/${path}`}><Icon size={16} aria-hidden="true" />{t(label)}</NavLink>)}</nav>
    <div className="locale" aria-label={t('common.language')}><button className={locale === 'es' ? 'active' : ''} aria-pressed={locale === 'es'} onClick={() => setLocale('es')}>ES</button><span aria-hidden="true">/</span><button className={locale === 'en' ? 'active' : ''} aria-pressed={locale === 'en'} onClick={() => setLocale('en')}>EN</button></div>
  </header>
}

function Seo() { const { pathname } = useLocation(); const { locale, t } = useI18n(); useEffect(() => { const title = pathname === '/' ? t('seo.homeTitle') : `${t(`pages.${pathname.slice(1)}.title`)} · ${t('brand')}`; document.title = title; document.documentElement.lang = locale; document.querySelector('meta[name="description"]')?.setAttribute('content', t('seo.description')); document.querySelector('meta[property="og:title"]')?.setAttribute('content', title); document.querySelector('meta[property="og:description"]')?.setAttribute('content', t('seo.description')); }, [locale, pathname, t]); return null }
function Footer() { const { t } = useI18n(); return <footer><div className="footer-brand"><img className="footer-logo" src="./project-logo.jpeg" alt={t('common.projectLogoAlt')} /><div><strong><em>Catopuma badia</em></strong><span>{t('footer.project')}</span><small>{t('footer.disclaimer')}</small></div></div><nav aria-label={t('footer.navigation')}><Link to="/sources">{t('nav.sources')}</Link><Link to="/methodology">{t('nav.methodology')}</Link><a href="https://github.com/thegreycatresearch/Borneo-Bay-Cat-Conservation-Genetics" target="_blank" rel="noreferrer">GitHub</a><a href="/CITATION.cff">{t('footer.citation')}</a></nav><small>{new Date().getFullYear()} · {t('footer.openData')}</small></footer> }
function Layout() { return <><Seo /><Header /><main><Routes><Route path="/" element={<Home />} /><Route path="/genetics" element={<GeneticsPage />} /><Route path="/distribution" element={<DistributionPage />} /><Route path="/taxonomy" element={<TaxonomyPage />} /><Route path="/profile" element={<SpeciesProfilePage />} /><Route path="/availability" element={<DataAvailabilityPage />} /><Route path="/research" element={<ResearchPage />} /><Route path="/conservation" element={<Conservation />} /><Route path="/explorer" element={<DataExplorerPage />} /><Route path="/sources" element={<Sources />} /><Route path="/methodology" element={<Methodology />} /><Route path="*" element={<NotFound />} /></Routes></main><Footer /></> }

function Home() {
  const { t } = useI18n(); const cards = [['genetic', Dna, 'genetics'], ['occurrence', Globe2, 'distribution'], ['literature', Search, 'research'], ['conservation', ShieldCheck, 'conservation']] as const
  return <div className="page home"><section className="hero"><div className="hero-copy"><p className="eyebrow">{t('home.eyebrow')}</p><h1>{t('home.title')}</h1><p className="subtitle">{t('home.subtitle')} <em>Catopuma badia</em></p><p className="hero-description">{t('home.description')}</p><div className="hero-tags"><span>{t('home.endangered')}</span><span>{t('home.endemic')}</span><span>{t('home.studied')}</span></div><div className="actions"><Link className="button primary" to="/explorer">{t('home.explore')} <ArrowUpRight size={17} /></Link><Link className="button quiet" to="/profile">{t('nav.profile')}</Link></div></div><div className="hero-species" role="img" aria-label={t('home.speciesVisualAlt')}><div className="species-ring"><span>CB</span></div><p><em>Catopuma badia</em><br /><small>{t('home.commonName')}</small></p></div></section>
    <section className="home-context"><div><p className="eyebrow">{t('home.whyKicker')}</p><h2>{t('home.whyTitle')}</h2></div><p>{t('home.whyText')}</p></section>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">{t('home.availability')}</p><h2>{t('home.summary')}</h2></div><span className="live-dot">● {t('home.observed')}</span></div><p className="muted intro">{t('home.summaryText')}</p><div className="metric-grid">{cards.map(([key, Icon, path]) => <Link className="metric" to={`/${path}`} key={key}><Icon size={20} /><span>{t(`home.${key}`)}</span><strong>{t(`home.${key}Value`)}</strong><small>{t(`home.${key}Note`)}</small></Link>)}</div></section>
    <section className="lower-grid"><Link className="panel map-note map-link" to="/distribution"><div className="panel-title"><div><p className="eyebrow">{t('home.mapKicker')}</p><h2>{t('home.map')}</h2></div><Globe2 size={22} aria-hidden="true" /></div><div className="map-placeholder" role="img" aria-label={t('home.mapAlt')}><span>Borneo</span><strong>GBIF</strong></div><p className="muted">{t('home.mapText')}</p></Link><div className="panel provenance"><p className="eyebrow">{t('home.sources')}</p><h2>{t('home.evidence')}</h2><div className="source-line"><span>01</span><p><strong>GBIF</strong><small>{t('sources.gbif')}</small></p></div><div className="source-line"><span>02</span><p><strong>NCBI / GenBank</strong><small>{t('sources.ncbi')}</small></p></div><div className="source-line"><span>03</span><p><strong>PubMed · Crossref</strong><small>{t('sources.pubmed')}</small></p></div></div></section>
    <section className="home-limitations"><p className="eyebrow">{t('home.limitsKicker')}</p><h2>{t('home.limitsTitle')}</h2><p>{t('home.limitsText')}</p><Link className="button quiet" to="/methodology">{t('home.limitsLink')} <ArrowUpRight size={15} /></Link></section>
  </div>
}

function PageHeader({ page }: { page: keyof typeof import('./i18n/en/common.json')['pages'] }) { const { t } = useI18n(); return <section className="page-header"><p className="eyebrow">{t(`pages.${page}.kicker`)}</p><h1>{t(`pages.${page}.title`)}</h1><p>{t(`pages.${page}.description`)}</p></section> }

function Genetics() { const { t } = useI18n(); const resource = useResource(fetchGeneticRecords); const result = resource.data; return <div className="page"><PageHeader page="genetics" /><div className="toolbar"><button className="button primary" onClick={resource.load} disabled={resource.loading}><Dna size={17} />{t('genetics.search')}</button><span className="data-badge">NCBI · E-utilities · public</span></div><StatusMessage loading={resource.loading} error={resource.error} empty={!!result && result.records.length === 0} />{result && <div className="panel table-wrap"><div className="table-summary"><strong>{result.count}</strong> {t('genetics.records')}</div><table><thead><tr><th>{t('genetics.accession')}</th><th>{t('common.scientificName')}</th><th>{t('genetics.marker')}</th><th>{t('genetics.length')}</th><th>{t('common.source')}</th></tr></thead><tbody>{result.records.map((record) => <tr key={record.sourceId}><td><a href={record.originalUrl} target="_blank" rel="noreferrer">{record.accession}</a></td><td><em>{record.scientificName}</em></td><td>{record.marker || '—'}</td><td>{record.sequenceLength || '—'}</td><td>{record.source}</td></tr>)}</tbody></table></div>}<div className="notice"><Dna size={19} /><span>{t('genetics.warning')}</span></div></div> }

function Distribution() { const { t } = useI18n(); const resource = useResource(fetchOccurrences); const result = resource.data; const current: OccurrenceRecord[] = result?.records || []; return <div className="page"><PageHeader page="distribution" /><div className="toolbar"><button className="button primary" onClick={resource.load} disabled={resource.loading}><Globe2 size={17} />{t('distribution.search')}</button><span className="data-badge">GBIF Occurrence API · limit 25</span></div><StatusMessage loading={resource.loading} error={resource.error} empty={!!result && result.records.length === 0} /><div className="distribution-grid"><div className="panel map-panel"><div className="panel-title"><h2>{t('distribution.map')}</h2><span>{current.filter((record) => record.latitude !== undefined).length} {t('common.records')}</span></div><MapView records={current} /></div><div className="panel stats-panel"><div className="stat"><span>{t('distribution.total')}</span><strong>{result?.count || '—'}</strong></div><div className="stat"><span>{t('distribution.georeferenced')}</span><strong>{current.filter((record) => record.latitude !== undefined).length || '—'}</strong></div><div className="stat"><span>{t('distribution.range')}</span><strong>—</strong></div><p className="muted">{t('distribution.precision')}</p></div></div>{current.length > 0 && <div className="panel table-wrap"><table><thead><tr><th>{t('common.scientificName')}</th><th>{t('common.country')}</th><th>{t('common.dataset')}</th><th>{t('common.institution')}</th><th>GBIF ID</th></tr></thead><tbody>{current.map((record) => <tr key={record.sourceId}><td><em>{record.scientificName}</em></td><td>{record.country || '—'}</td><td>{record.dataset || '—'}</td><td>{record.institution || '—'}</td><td><a href={record.originalUrl} target="_blank" rel="noreferrer">{record.sourceId}</a></td></tr>)}</tbody></table></div>}</div> }

function SimplePage({ page }: { page: 'research' | 'explorer' }) { const { t } = useI18n(); return <div className="page"><PageHeader page={page} /><div className="empty-state"><Database size={30} /><h2>{t('common.notConnected')}</h2><p>{t('common.empty')}</p></div></div> }
function Conservation() { const { t } = useI18n(); const sections = ['status', 'habitat', 'capture', 'forest', 'protected', 'gaps', 'genetics', 'priorities', 'project']; return <div className="page"><PageHeader page="conservation" /><div className="notice"><ShieldCheck size={18} /><span>{t('conservation.disclaimer')}</span></div><div className="conservation-grid detailed">{sections.map((key, index) => <section className="panel conservation-card" key={key}><span className="source-number">0{index + 1}</span><h2>{t(`conservation.${key}Title`)}</h2><p>{t(`conservation.${key}Text`)}</p>{key === 'status' && <a href="https://www.catsg.org/" target="_blank" rel="noreferrer" className="button quiet">{t('conservation.external')} <ArrowUpRight size={16} /></a>}</section>)}</div></div> }
function Sources() { const { t } = useI18n(); const items = ['gbif', 'ncbi', 'pubmed', 'crossref', 'bold', 'dryad', 'iucn']; const links: Record<string, string> = { gbif: 'https://www.gbif.org/', ncbi: 'https://www.ncbi.nlm.nih.gov/', pubmed: 'https://pubmed.ncbi.nlm.nih.gov/', crossref: 'https://www.crossref.org/', bold: 'https://www.boldsystems.org/', dryad: 'https://datadryad.org/', iucn: 'https://www.catsg.org/' }; return <div className="page"><PageHeader page="sources" /><div className="source-grid detailed">{items.map((item, index) => { const connection = item === 'iucn' ? 'referenced' : item === 'gbif' || item === 'ncbi' || item === 'pubmed' || item === 'crossref' || item === 'dryad' || item === 'bold' ? 'direct' : 'planned'; return <div className="panel source-card" key={item}><span className="source-number">0{index + 1}</span><h2>{item === 'ncbi' ? 'NCBI / GenBank' : item === 'iucn' ? 'Cat Specialist Group / IUCN' : item.toUpperCase()}</h2><p>{t(`sources.${item}`)}</p><dl><dt>{t('sources.data')}</dt><dd>{t(`sources.${item}`)}</dd><dt>{t('sources.notData')}</dt><dd>{t(`sources.${item}`)}</dd><dt>{t('sources.connection')}</dt><dd>{t(`sources.${connection}`)}</dd><dt>{t('sources.retrieval')}</dt><dd>{t(`sources.${connection === 'direct' ? 'onQuery' : 'notApplicable'}`)}</dd></dl><a href={links[item]} target="_blank" rel="noreferrer">{t('common.learnMore')} <ArrowUpRight size={14} /></a></div> })}</div></div> }
function Methodology() { const { t } = useI18n(); const sections = [['retrieval', 'retrievalTitle'], ['coordinates', 'coordinatesTitle'], ['taxonomy', 'taxonomyTitle'], ['provenance', 'provenanceTitle'], ['direct', 'direct'], ['derived', 'derived'], ['refresh', 'refresh'], ['limits', 'limits'], ['unknown', 'unknown'], ['inference', 'inferenceTitle']] as const; return <div className="page"><PageHeader page="methodology" /><div className="notice"><Dna size={18} /><span>{t('methodology.inferenceText')}</span></div><div className="method-grid">{sections.map(([key, title], index) => <div className="method-item" key={key}><span>{String(index + 1).padStart(2, '0')}</span><div><h2>{t(`methodology.${title}`)}</h2><p>{t(`methodology.${key}Text`)}</p></div></div>)}</div></div> }
function NotFound() { const { t } = useI18n(); return <div className="page"><div className="empty-state"><h1>{t('common.notFound')}</h1><p>{t('common.notFoundText')}</p><Link className="button primary" to="/">{t('nav.home')}</Link></div></div> }

export default function App() { return <HashRouter><Layout /></HashRouter> }
