import { useState } from 'react'
import { HashRouter, Link, NavLink, Route, Routes } from 'react-router-dom'
import { ArrowUpRight, BarChart3, Database, Dna, Globe2, Leaf, Menu, Search, ShieldCheck, X } from 'lucide-react'
import { useI18n } from './i18n'
import { fetchGeneticRecords } from './services/ncbi'
import { fetchOccurrences } from './services/gbif'
import { useResource } from './hooks/useResource'
import { MapView } from './components/MapView'
import { StatusMessage } from './components/StatusMessage'
import type { OccurrenceRecord } from './types'
import { DistributionPage, GeneticsPage, DataExplorerPage, TaxonomyPage, ResearchPage, DataAvailabilityPage, SpeciesProfilePage } from './pages'
import './styles.css'

const routes = [
  ['genetics', 'nav.genetics', Dna], ['distribution', 'nav.distribution', Globe2], ['taxonomy', 'nav.taxonomy', Database], ['profile', 'nav.profile', Leaf], ['availability', 'nav.availability', BarChart3], ['research', 'nav.research', Search],
  ['conservation', 'nav.conservation', ShieldCheck], ['explorer', 'nav.explorer', Database], ['sources', 'nav.sources', Leaf], ['methodology', 'nav.methodology', Database]
] as const

function Header() {
  const { locale, setLocale, t } = useI18n(); const [open, setOpen] = useState(false)
  return <header className="site-header"><Link className="brand" to="/"><span className="brand-mark">BB</span><span><strong>{t('brand')}</strong><small>{t('brandSub')}</small></span></Link>
    <button className="menu-button" aria-label="Menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
    <nav className={open ? 'nav open' : 'nav'}>{routes.map(([path, label, Icon]) => <NavLink onClick={() => setOpen(false)} key={path} to={`/${path}`}><Icon size={16} />{t(label)}</NavLink>)}</nav>
    <div className="locale" aria-label="Language selector"><button className={locale === 'es' ? 'active' : ''} onClick={() => setLocale('es')}>ES</button><span>/</span><button className={locale === 'en' ? 'active' : ''} onClick={() => setLocale('en')}>EN</button></div>
  </header>
}

function Layout() { return <><Header /><main><Routes><Route path="/" element={<Home />} /><Route path="/genetics" element={<GeneticsPage />} /><Route path="/distribution" element={<DistributionPage />} /><Route path="/taxonomy" element={<TaxonomyPage />} /><Route path="/profile" element={<SpeciesProfilePage />} /><Route path="/availability" element={<DataAvailabilityPage />} /><Route path="/research" element={<ResearchPage />} /><Route path="/conservation" element={<Conservation />} /><Route path="/explorer" element={<DataExplorerPage />} /><Route path="/sources" element={<Sources />} /><Route path="/methodology" element={<Methodology />} /></Routes></main><footer><span>Catopuma badia</span><span>{new Date().getFullYear()} · Open research data</span></footer></> }

function Home() {
  const { t } = useI18n(); const cards = [['genetic', Dna, 'genetics'], ['occurrence', Globe2, 'distribution'], ['literature', Search, 'research'], ['conservation', ShieldCheck, 'conservation']] as const
  return <div className="page home"><section className="hero"><div className="hero-copy"><p className="eyebrow">{t('home.eyebrow')}</p><h1>{t('home.title')}</h1><p className="subtitle">{t('home.subtitle')} <em>Catopuma badia</em></p><p className="hero-description">{t('home.description')}</p><div className="actions"><Link className="button primary" to="/explorer">{t('home.explore')} <ArrowUpRight size={17} /></Link><Link className="button quiet" to="/methodology">{t('home.method')}</Link></div></div><div className="hero-species"><div className="species-ring"><span>CB</span></div><p><em>Catopuma badia</em><br /><small>Bornean bay cat</small></p></div></section>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">{t('home.availability')}</p><h2>{t('home.summary')}</h2></div><span className="live-dot">● {t('home.observed')}</span></div><p className="muted intro">{t('home.summaryText')}</p><div className="metric-grid">{cards.map(([key, Icon, path]) => <Link className="metric" to={`/${path}`} key={key}><Icon size={20} /><span>{t(`home.${key}`)}</span><strong>—</strong><small>{t('common.notConnected')}</small></Link>)}</div></section>
    <section className="lower-grid"><div className="panel map-note"><div className="panel-title"><div><p className="eyebrow">{t('home.map')}</p><h2>{t('home.map')}</h2></div><Globe2 size={22} /></div><div className="map-placeholder"><span>01°N · 110°E</span><strong>GBIF</strong></div><p className="muted">{t('home.mapText')}</p></div><div className="panel provenance"><p className="eyebrow">{t('home.sources')}</p><h2>{t('home.evidence')}</h2><div className="source-line"><span>01</span><p><strong>GBIF</strong><small>{t('sources.gbif')}</small></p></div><div className="source-line"><span>02</span><p><strong>NCBI / GenBank</strong><small>{t('sources.ncbi')}</small></p></div><div className="source-line"><span>03</span><p><strong>PubMed · Crossref</strong><small>{t('sources.pubmed')}</small></p></div></div></section>
  </div>
}

function PageHeader({ page }: { page: keyof typeof import('./i18n/en/common.json')['pages'] }) { const { t } = useI18n(); return <section className="page-header"><p className="eyebrow">{t(`pages.${page}.kicker`)}</p><h1>{t(`pages.${page}.title`)}</h1><p>{t(`pages.${page}.description`)}</p></section> }

function Genetics() { const { t } = useI18n(); const resource = useResource(fetchGeneticRecords); const result = resource.data; return <div className="page"><PageHeader page="genetics" /><div className="toolbar"><button className="button primary" onClick={resource.load} disabled={resource.loading}><Dna size={17} />{t('genetics.search')}</button><span className="data-badge">NCBI · E-utilities · public</span></div><StatusMessage loading={resource.loading} error={resource.error} empty={!!result && result.records.length === 0} />{result && <div className="panel table-wrap"><div className="table-summary"><strong>{result.count}</strong> {t('genetics.records')}</div><table><thead><tr><th>{t('genetics.accession')}</th><th>{t('common.scientificName')}</th><th>{t('genetics.marker')}</th><th>{t('genetics.length')}</th><th>{t('common.source')}</th></tr></thead><tbody>{result.records.map((record) => <tr key={record.sourceId}><td><a href={record.originalUrl} target="_blank" rel="noreferrer">{record.accession}</a></td><td><em>{record.scientificName}</em></td><td>{record.marker || '—'}</td><td>{record.sequenceLength || '—'}</td><td>{record.source}</td></tr>)}</tbody></table></div>}<div className="notice"><Dna size={19} /><span>{t('genetics.warning')}</span></div></div> }

function Distribution() { const { t } = useI18n(); const resource = useResource(fetchOccurrences); const result = resource.data; const current: OccurrenceRecord[] = result?.records || []; return <div className="page"><PageHeader page="distribution" /><div className="toolbar"><button className="button primary" onClick={resource.load} disabled={resource.loading}><Globe2 size={17} />{t('distribution.search')}</button><span className="data-badge">GBIF Occurrence API · limit 25</span></div><StatusMessage loading={resource.loading} error={resource.error} empty={!!result && result.records.length === 0} /><div className="distribution-grid"><div className="panel map-panel"><div className="panel-title"><h2>{t('distribution.map')}</h2><span>{current.filter((record) => record.latitude !== undefined).length} {t('common.records')}</span></div><MapView records={current} /></div><div className="panel stats-panel"><div className="stat"><span>{t('distribution.total')}</span><strong>{result?.count || '—'}</strong></div><div className="stat"><span>{t('distribution.georeferenced')}</span><strong>{current.filter((record) => record.latitude !== undefined).length || '—'}</strong></div><div className="stat"><span>{t('distribution.range')}</span><strong>—</strong></div><p className="muted">{t('distribution.precision')}</p></div></div>{current.length > 0 && <div className="panel table-wrap"><table><thead><tr><th>{t('common.scientificName')}</th><th>{t('common.country')}</th><th>{t('common.dataset')}</th><th>{t('common.institution')}</th><th>GBIF ID</th></tr></thead><tbody>{current.map((record) => <tr key={record.sourceId}><td><em>{record.scientificName}</em></td><td>{record.country || '—'}</td><td>{record.dataset || '—'}</td><td>{record.institution || '—'}</td><td><a href={record.originalUrl} target="_blank" rel="noreferrer">{record.sourceId}</a></td></tr>)}</tbody></table></div>}</div> }

function SimplePage({ page }: { page: 'research' | 'explorer' }) { const { t } = useI18n(); return <div className="page"><PageHeader page={page} /><div className="empty-state"><Database size={30} /><h2>{t('common.notConnected')}</h2><p>{t('common.empty')}</p></div></div> }
function Conservation() { const { t } = useI18n(); return <div className="page"><PageHeader page="conservation" /><div className="conservation-grid"><div className="panel conservation-card"><ShieldCheck size={30} /><p className="eyebrow">{t('common.source')}</p><h2>{t('conservation.iucn')}</h2><p>{t('conservation.note')}</p><a href="https://www.catsg.org/" target="_blank" rel="noreferrer" className="button quiet">{t('conservation.external')} <ArrowUpRight size={16} /></a></div></div></div> }
function Sources() { const { t } = useI18n(); const items = ['gbif', 'ncbi', 'bold', 'pubmed', 'crossref', 'dryad', 'iucn']; return <div className="page"><PageHeader page="sources" /><div className="source-grid">{items.map((item, index) => <div className="panel source-card" key={item}><span className="source-number">0{index + 1}</span><h2>{item === 'ncbi' ? 'NCBI / GenBank' : item.toUpperCase()}</h2><p>{t(`sources.${item}`)}</p><a href={item === 'gbif' ? 'https://www.gbif.org/' : item === 'ncbi' ? 'https://www.ncbi.nlm.nih.gov/' : item === 'bold' ? 'https://www.boldsystems.org/' : item === 'pubmed' ? 'https://pubmed.ncbi.nlm.nih.gov/' : item === 'crossref' ? 'https://www.crossref.org/' : item === 'dryad' ? 'https://datadryad.org/' : 'https://www.catsg.org/'} target="_blank" rel="noreferrer">{t('common.learnMore')} <ArrowUpRight size={14} /></a></div>)}</div></div> }
function Methodology() { const { t } = useI18n(); return <div className="page"><PageHeader page="methodology" /><div className="method-grid">{['direct', 'derived', 'limits', 'refresh', 'unknown'].map((key, index) => <div className="method-item" key={key}><span>{String(index + 1).padStart(2, '0')}</span><div><h2>{t(`methodology.${key}`)}</h2><p>{t(`methodology.${key}Text`)}</p></div></div>)}</div></div> }

export default function App() { return <HashRouter><Layout /></HashRouter> }
